---

- name: Install ferm required packages
  apt:
    state: present
    name: ferm
  notify: restart ferm

- name: Copy ferm configuration
  template:
    src: templates/ferm.conf
    dest: /etc/ferm/ferm.conf
    backup: yes
  notify: restart ferm
