---

name: Deploy new galaxy version

on:
  create:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Sets RELEASE_VERSION to be refs/tags/v<version> -> <version>
      - name: Get the version from the tag
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF#refs/tags/v})

      - name: Upload to ansible-galaxy
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          galaxy_version: '${{ env.RELEASE_VERSION }}'